# THEME CONFIGURATION
title: Corne # your site
author: Github User
description: > # Description of website
  Some wonderful description for the website.
baseurl: "/corne" # The subpath for the website, e.g.: /shop, /blog
url: "https://eudaldgr.github.io" # The hostname, e.g.: https://www.example.org

jumbo_img: assets/cover.jpg # The background image

sass:
  sass_dir: _sass
  style: compressed
